config/routes.rb
Rails.application.routes.draw do
  root 'uploaders#index'
  resources :uploaders
  get '/signup' => 'users#new'
  get 'logout' => 'sessions#logout'
  get '/admin_area' => 'users#admin_area'
  resources :users
  resources :sessions

end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
  validates :name, :presence => true, :length => { :in => 4..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true, :length => { :in => 6..30 }
  
  before_save :create_hashed_password, :default_values
  
  has_many :z_files
  
  private
  def create_hashed_password
    self.password = Digest::MD5.hexdigest(self.password)
  end

  def default_values
    self.role ||= 'user'
  end
  
  public
  def authenticate
    user = User.find_by_email(self.email)
    if user && user.password == create_hashed_password
      return user
    else
      return false
    end
  end

end

app/models/z_file.rb
class ZFile < ActiveRecord::Base
  DIRECTORY = Dir.pwd + "/public/files"
  attr_accessor :tempfile
  belongs_to :user
  validates :user, :presence => true
  validates :name, :presence => true
  
  def save_file
    begin
      # Generate a random name for the file
      random_string = (0...15).map { (65 + rand(26)).chr }.join
      # Find the extension
      name_split = self.name.split('.')
      if name_split.length == 1
        ext = "txt"
      else
        ext = name_split[-1]
      end
      # create a new file name using random string and extension
      destination_name = random_string + "." + ext
      # save the file and move it to the directory
      path = File.join(DIRECTORY, destination_name)
      FileUtils.move self.tempfile, path
      self.file_hash = destination_name
      if self.save
        return true
      else
        return false
      end
    rescue
      return false
    end
  end

  def get_file_path
    File.join(DIRECTORY, self.file_hash)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :admin?

  def admin?
    if @current_user.role == "admin"
      return true
    else
      return false
    end
  end

  def authenticated?
    if session[:user_id]
      @current_user = User.find(session[:user_id])
      return true
    else
      redirect_to(:controller => "sessions", :action => "new")
      return false
    end
  end

  def not_authenticated?
    if !session[:user_id]
      return true
    else
      redirect_to "/"
    end
  end

  def is_admin?
    if @current_user.role == "admin"
      return true
    else
      flash[:message] = "Refrain from entering the admin area"
      redirect_to '/'
      return false
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authenticated?, only: [:logout]
  before_filter :not_authenticated?, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:password, :email))
    login_user = @user.authenticate
    if login_user
      session[:user_id] = login_user.id
      flash[:notice] = "Successful Login for " + login_user.name
      redirect_to '/'
    else
      flash[:notice] = "Invalid username or password"
      render "new"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/uploaders_controller.rb
class UploadersController < ApplicationController
  before_filter :authenticated?

  def index
    @files = @current_user.z_files
  end

  def create
    zfile = params['zfile']
    @file = @current_user.z_files.new
    @file.name = zfile.original_filename
    @file.tempfile = zfile.tempfile
    if @file.save_file
      flash[:message] = "File saved successfully"
    else
      flash[:message] = "Could not save file due to some error"
    end
    redirect_to '/'
  end

  def show
    begin
      if admin?
        zfile = ZFile.find(params[:id])
      else
        zfile = @current_user.z_files.find(params[:id])
      end
      send_file(zfile.get_file_path, filename: zfile.name)
    rescue
      render plain: "You don't have access to this file"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticated?, only: [:admin_area, :show]
  before_filter :is_admin?, only: [:admin_area, :show]
  before_filter :not_authenticated?, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:message] = "Account created successfully"
      redirect_to "/"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  public
  def admin_area
    @users = User.all
  end

  def show
    user = User.find(params[:id])
    @files = user.z_files
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/uploaders_helper.rb
module UploadersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Megaupload</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploaders/index.html.erb
<% flash.each do |key, val| %>
  <b><%= val %></b>
<% end %>
<h3>Files</h3>
<ul>
  <% @files.each do |file| %>
    <li><%= link_to file.name, uploader_path(file)%></li>
  <% end %>
</ul>

<h4>Add new</h4>
<%= form_tag({:action => :create }, multipart: true) do |f| %>
  <p><%= file_field_tag 'zfile' %>
  <p><%= submit_tag("Upload") %></p>
<% end %>
<% if admin? %>
  <p><%= link_to('Admin Area', :controller => "users", :action => "admin_area") %></p>
<% end %>
<%= link_to 'Logout', '/logout' %>

app/views/users/admin_area.html.erb
<h3>Users</h3>

<ul>
  <% @users.each do |u| %>
    <li><%= link_to u.name, user_path(u) %></li>
  <% end %>
</ul>

<p><%= link_to "Home", uploaders_path %></p>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <h4>Following errors came up</h4>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p> Name : <%= f.text_field :name %></p>
  <p> Email : <%= f.email_field :email %></p>
  <p> Password : <%= f.password_field :password %></p>
  <p> Password Confirmation : <%= f.password_field :password_confirmation %></p>
  <p> <%= f.submit "Sign Up" %></p>
<% end %>

<br>
<p> Or <%= link_to("Login", :controller => "sessions", :action => "new") %></p>

app/views/users/show.html.erb
<h3>Files</h3>

<ul>
  <% @files.each do |f| %>
    <li><%= link_to f.name, uploader_path(f) %></li>
  <% end %>
</ul>

<p><%= link_to "Home", uploaders_path %></p>